# Generated by Django 3.2.6 on 2021-08-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_bookmodel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
