# Generated by Django 3.2.6 on 2021-08-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
