# Generated by Django 3.2.6 on 2021-08-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_pdf',
            field=models.FileField(default=None, null=True, upload_to='ebook-pdf'),
        ),
    ]
